### ISSUE TITLE
Template Strings Not Supported

### ISSUE THREAD

**Issue by ElectricCoffee** [thomblake/js3-mode#110]
[Template Strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings) are a neat feature in JS that lets you interpolate data into your strings using back-ticks (`` ` ``).

JS3 will say `` ` `` is an illegal character and render the string incorrectly

**Comment by thomblake** [comment]
Yeah in general js3-mode's version of Rhino doesn't support new es6 syntax.

**Comment by thomblake** [comment]
Actually closing this as duplicate of #107
