### ISSUE TITLE
Mode is not working with ES6 template string literals

### ISSUE THREAD

**Issue by alissonperez** [thomblake/js3-mode#116]
With js-mode string-literals works properly. But js3-mode is not understanding its syntax.

![screen shot 2017-04-07 at 6 19 53 pm](https://cloud.githubusercontent.com/assets/756802/24820384/1948cc54-1bbf-11e7-984e-916f224c9d7a.png)

Do you know if it's a limitation of js3-mode or can be a wrong/missing config?

My emacs version is `25.1.1`.

Thanks!

**Comment by tamzinblake** [comment]
js3-mode's parser was written before those were a thing. js3-mode isn't currently maintained. You may want to check out js2-mode, or feel free to file a PR.

**Comment by alissonperez** [comment]
Ok, understood! Thanks @thomblake !
